### ISSUE TITLE
[FEATURE] Events Page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#100]
### Detailed description

Add an Events page for the community, so they can active in the community and can participate in events.

### Context

- With events, community members can act in the community and can participate in events.

### Possible implementation

This is our events page: 
![image](https://user-images.githubusercontent.com/44284877/192701359-72ddc0f7-8c5f-4e40-abc4-06de004fab68.png)
you can remove the content of the events from this page.
our website's events page: https://www.thecyberhub.org/resources/events

---

We have to make a page like this:  
![image](https://user-images.githubusercontent.com/44284877/192701178-e6ebd9ad-b2f6-46e9-bb23-799e25fdcec2.png)

### Additional information

If you want to work on this issue let us know we will assign you.

if you have questions to ask. ask below.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by mohakgupt** [comment]
Can I do it? I know React

**Comment by kabir0x23** [comment]
> Can I do it? I know React

Yes, sure.
you can make a page similar to as mentioned above
the main focus is now centered part.

I am assignig you the task.

**Comment by kabir0x23** [comment]
> Can I do it? I know React

Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

+ You will get more green squares

**Comment by mohakgupt** [comment]
> > Can I do it? I know React
> 
> Will you checkout this repository frist? https://github.com/CryptoverseWeb3/git-github-practice
> 
> * You will get more green squares

Yeah thanks

**Comment by mohakgupt** [comment]
![image](https://user-images.githubusercontent.com/100181077/193409030-adfc7ac8-e7d5-41a5-b2e1-9a53118122d8.png)
How is this layout?

**Comment by mohakgupt** [comment]
![image](https://user-images.githubusercontent.com/100181077/193409139-25e071da-2b77-4e62-a4dc-2cb542aae11f.png)
How is this layout?

**Comment by kabir0x23** [comment]
> ![image](https://user-images.githubusercontent.com/100181077/193409139-25e071da-2b77-4e62-a4dc-2cb542aae11f.png) How is this layout?

looks good 
Nice work @mohakgupt
