### ISSUE TITLE
[FEATURE] Dropdown navbar

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#101]
### Detailed description

Nav bar
We have this type of navbar

If you click on any Item, it will smooth scroll down.
![image](https://user-images.githubusercontent.com/44284877/192752082-9c70fd0a-3865-46a8-acf2-8e91d31a7a8d.png)

for each each sub-sections, we have different navbars
so it becomes complex to use for new users.

If you will have any confusion, disscuss beflow: 👇

### Context

So we are looking for an on-hover and on-clicked drop-down navbar.
like: ![image](https://user-images.githubusercontent.com/44284877/192751858-1bd94a48-b8d9-478a-ab6f-48d4ee65cc5a.png)

but when we click the top nav item it should smooth scroll down, as it is working now

example resources nav-item:
so on-hover and on-clicked on resources navbar
![image](https://user-images.githubusercontent.com/44284877/192753465-4b15a0df-b76b-40b2-bdc0-3a3a5ecf8034.png)

it should display it's below content:
![image](https://user-images.githubusercontent.com/44284877/192754699-32bd2623-8a76-420c-a566-7680dbf70269.png)

and after 
on-hover and on-clicked on prep navbar-item
these items should be displayed
![image](https://user-images.githubusercontent.com/44284877/192754428-4bfb909f-7b53-4d79-904d-64f6e5fc658a.png)

If we have on the resources section
only we have to add on hove dropdown.

With this.
- User experience will be good
- Easy to use

### Possible implementation

This type of navbar is easy for navigation.
![image](https://user-images.githubusercontent.com/44284877/192751858-1bd94a48-b8d9-478a-ab6f-48d4ee65cc5a.png)

### Additional information

If you have any questions or doubts feel free to discuss them below.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by codewithnadeem14502** [comment]
hello sir/mam, i want to contribute to it, can you assign me this issue and i am completely new to open source

**Comment by saimaheshtaduri** [comment]
I would like to contribute. if there's room, assign this issue to me. @kabir0x23

**Comment by hritesh94** [comment]
Can we Bootstrap for implementing the dropdown feature or tailwind css is the only option?

**Comment by kabir0x23** [comment]
> I would like to contribute. if there's room, assign this issue to me. @kabir0x23

Will you contribute here frist.
- will you first checkout this repo:
https://github.com/cryptoverseWeb3/git-github-practice

I will assign you this issue

**Comment by kabir0x23** [comment]
@saimaheshtaduri

**Comment by Muhammad-Shahid-Jamal** [comment]
Hi @kabir0x23  I would like to contribute to this issue, assign this issue to me

**Comment by yunsuklee** [comment]
Hey man! I'd love to try contributing to your project, let me know if I can be of any help :)

**Comment by Muhammad-Shahid-Jamal** [comment]
> Hi @kabir0x23 I would like to contribute to this issue, assign this issue to me

I need more info about it do you need only a hover type ladder based menu just for the desktop or do you need it also on mobile devices? @kabir0x23

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 I would like to contribute to this issue, assign this issue to me

Will you contribute here frist.

    will you first checkout this repo:
    https://github.com/cryptoverseWeb3/git-github-practice

I will assign you this issue

**Comment by kabir0x23** [comment]
> Hey man! I'd love to try contributing to your project, let me know if I can be of any help :)

Will you contribute here frist. you will get more green sqaures

    will you first checkout this repo:
    https://github.com/cryptoverseWeb3/git-github-practice

I will assign you this issue

**Comment by Muhammad-Shahid-Jamal** [comment]
> > Hi @kabir0x23 I would like to contribute to this issue, assign this issue to me
> 
> Will you contribute here frist. you will get more green sqaures
> 
> * will you first checkout this repo:
> * https://github.com/cryptoverseWeb3/git-github-practice
> 
> I will assign you this issue

@kabir0x23  its done

**Comment by Saurav-Singh-Rauthan** [comment]
![image](https://user-images.githubusercontent.com/54982868/193439386-9e8dcf2d-3d7a-4452-90b0-388d28fa5018.png)
are you looking for something like this? @kabir0x23

**Comment by Saurav-Singh-Rauthan** [comment]
> ![image](https://user-images.githubusercontent.com/54982868/193439386-9e8dcf2d-3d7a-4452-90b0-388d28fa5018.png) are you looking for something like this? @kabir0x23

i can give it a try

**Comment by kabir0x23** [comment]
> > ![image](https://user-images.githubusercontent.com/54982868/193439386-9e8dcf2d-3d7a-4452-90b0-388d28fa5018.png) are you looking for something like this? @kabir0x23
> 
> i can give it a try

already shared the example above
must give a look

**Comment by kabir0x23** [comment]
@Muhammad-Shahid-Jamal @saimaheshtaduri @Saurav-Singh-Rauthan @yunsuklee 
This issue is in high priority (if possible, we want it by today or max tomorrow)

If anyone from you is want to do let me know,I will assign this issue to you
Thanks,

**Comment by saimaheshtaduri** [comment]
@kabir0x23 I will try it out. assign to me

**Comment by kabir0x23** [comment]
> @kabir0x23 I will try it out. assign to me

assigned ✔

**Comment by saimaheshtaduri** [comment]
can I use react bootstrap library ? @kabir0x23

**Comment by kabir0x23** [comment]
> can I use react bootstrap library ? @kabir0x23

nope we are using styled-components here,so you can use only styled-components or direct CSS
If you will have any doubts or questions, let us know.

**Comment by kabir0x23** [comment]
> can I use react bootstrap library ? @kabir0x23

you can watch this video if you got stuck, as a reference https://youtu.be/T2MhVxJxsL0

**Comment by saimaheshtaduri** [comment]
@kabir0x23  I have just raised a pr, the sample is ready. The code can be improved for sure.. This is just to confirm whether I am on right track on not. If yes, let me know I can raise another issue and work on the code improvisation. 
Thanks :)
