### ISSUE TITLE
[FEATURE] Quiz section: Add categories

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#102]
### Detailed description

We have a simple quiz section:
![image](https://user-images.githubusercontent.com/44284877/192759334-fa15aa04-b002-4786-9491-8ae540ebd38f.png)

so we want to improve it.

### Context

Here is an example:
![image](https://user-images.githubusercontent.com/44284877/192761451-01a7ef81-36a8-4e80-9e57-53f45f5841ed.png)

we have to mention
networking, security awareness etx
more examples:
![image](https://user-images.githubusercontent.com/44284877/192761629-4f9edbfc-c5cc-4953-87ad-2dd2669ea4c1.png)

### Possible implementation

after completing the above task we can move further.

### Additional information

if you have any questions or doubts, feel free to ask below. 👇

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aswinikalyan30** [comment]
Hey! can i take this up?

**Comment by kabir0x23** [comment]
> Hey! can i take this up?

Yes, go ahead, I am assigning you this issue.

First step is: 
 - Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

- + You will get more green squares

**Comment by saimaheshtaduri** [comment]
Is the issue still open? if yes, assign to me, I am interested to contribute. @kabir0x23

**Comment by kabir0x23** [comment]
> Is the issue still open? if yes, assign it to me, I am interested to contribute. @kabir0x23

Yes, this issue is still open.

and the First step is:
- Will you check out this repository first?
  - https://github.com/CryptoverseWeb3/git-github-practice
  - You will get more green squares with this

I will assign this issue to you.

**Comment by abdullmustyy** [comment]
Hi, @kabir0x23 

I have checked out the [repository ](https://github.com/CryptoverseWeb3/git-github-practice) repo. I am familiar with Git and GitHub flow and have seen that the repo is a Git and GitHub guide.

I'd be happy to take on this task. So, please assign the issue to me.

**Comment by kabir0x23** [comment]
> Hi, @kabir0x23
> 
> I have checked out the [repository ](https://github.com/CryptoverseWeb3/git-github-practice). I am familiar with Git and GitHub flow and have seen that the repo is a Git and GitHub guide.
> 
> I'd be happy to take on this task. So, please assign the issue to me.

Awesome, I am assigning this issue to you.
If you will have any doubts and questions, let us know.

**Comment by abdullmustyy** [comment]
> > Hi, @kabir0x23
> > I have checked out the [repository ](https://github.com/CryptoverseWeb3/git-github-practice). I am familiar with Git and GitHub flow and have seen that the repo is a Git and GitHub guide.
> > I'd be happy to take on this task. So, please assign the issue to me.
> 
> Awesome, I am assigning this issue to you. If you will have any doubts and questions, let us know.

Thank you.

What's bothering me atm is:
In the first screenshot, there are only four options but in the second screenshot, there are seven slots for options. I want to confirm if the third screenshot will be the option replacement.

**Comment by kabir0x23** [comment]
We have to add these categories above there
We don't have to change the quiz section:
hope this image will clear your doubts:
![image](https://user-images.githubusercontent.com/44284877/193443698-32d2e348-1f30-43ed-8af7-2b640bf713f2.png)

If you will have any doubts and questions, let us know.

**Comment by abdullmustyy** [comment]
> We have to add these categories above there We don't have to change the quiz section: hope this image will clear your doubts: ![image](https://user-images.githubusercontent.com/44284877/193443698-32d2e348-1f30-43ed-8af7-2b640bf713f2.png)
> 
> If you will have any doubts and questions, let us know.

Alright, I get it. 
I'm on it. Thank you.

**Comment by abdullmustyy** [comment]
> > We have to add these categories above there We don't have to change the quiz section: hope this image will clear your doubts: ![image](https://user-images.githubusercontent.com/44284877/193443698-32d2e348-1f30-43ed-8af7-2b640bf713f2.png)
> > If you will have any doubts or questions, let us know.
> 
> Alright, I get it. I'm on it. Thank you.

Hi, @kabir0x23 

I'm sorry it's coming this late. I had to round a personal project of mine before jumping on this one. 
Anyways, here is what I have implemented. ➡️ [Image](https://im.ge/i/Screenshot-4.1KUekD)

I believe the UI looks nice the way I implemented it, but if you insist you want it the way it was in the demo, I'll need the UI specifications.

Question: Where do we get each category's question and options from?

**Comment by kabir0x23** [comment]
> > > We have to add these categories above there We don't have to change the quiz section: hope this image will clear your doubts: ![image](https://user-images.githubusercontent.com/44284877/193443698-32d2e348-1f30-43ed-8af7-2b640bf713f2.png)
> > > If you will have any doubts or questions, let us know.
> > 
> > Alright, I get it. I'm on it. Thank you.
> 
> Hi, @kabir0x23 
> 
> I'm sorry it's coming this late. I had to round off a personal project of mine before jumping on this one. 
> Anyways, here is what I have implemented. ➡️ [Image](https://im.ge/i/Screenshot-4.1KUekD)
> 
> I believe the UI looks nice the way I implemented it, but if you insist you want it the way it was in the demo, I'll need the UI specifications.
> 
> Question: Where do we get each category's question and options from, and may I proceed to make a PR?

It's awesome

**Comment by abdullmustyy** [comment]
> > Hi, @kabir0x23
> > I'm sorry it's coming this late. I had to round off a personal project of mine before jumping on this one.
> > Anyways, here is what I have implemented. ➡️ [Image](https://im.ge/i/Screenshot-4.1KUekD)
> > I believe the UI looks nice the way I implemented it, but if you insist you want it the way it was in the demo, I'll need the UI specifications.
> > Question: Where do we get each category's question and options from, and may I proceed to make a PR?
> 
> Hey. It's awesome
> 
> If you need dummy quiz data.
> 
> You can get from here. To implement this in exact way.
> 
> https://www.ftc.gov/business-guidance/small-businesses/cybersecurity/quiz

Thank you.
I'd get to it now.

I have just made a PR, please review it.

**Comment by kabir0x23** [comment]
> > Hey. It's awesome
> > 
> > If you need dummy quiz data.
> > 
> > You can get from here. To implement this in exact way.
> > 
> > https://www.ftc.gov/business-guidance/small-businesses/cybersecurity/quiz
> 
> Thank you.
> I'd get to it now.
> 
> I have just made a PR, please review it.


You still can improvement above questions
In the same PR and have to push the code 

It will be automatically reflect on the same PR

If you will going to add above stuff 
Then it will be more valuable for hacktoberfest.

**Comment by abdullmustyy** [comment]
Hi, @kabir0x23 

I have implemented the functionalities, see a video of how it is. ➡️ [Video](https://vimeo.com/756829750)

**Comment by abdullmustyy** [comment]
> Hi, @kabir0x23
> 
> I have implemented the functionalities, see a video of how it is. ➡️ [Video](https://vimeo.com/756829750)

@kabir0x23 

I have just made a PR, please review it. Thank you.
