### ISSUE TITLE
[Bug] Not Responsive on Smaller Screens

### ISSUE THREAD

**Issue by sumitbishti** [thecyberworld/thecyberhub.org#103]
### Describe the bug

1. A part of navbar is collapsing on smaller screens. 
2.  And there is overflow on x-axis on smaller screens.

### To Reproduce

1. Open the Website
2. Change the resolution of the window to smaller sizes.
3. Scroll left to right to see the defect.

### Expected Behavior

Shouldn't be no overflow at x-axis and navbar elements shouldn't collapse with one-another on smaller sizes

### Screenshot/ Video

Right side hamburger menu half-appearing.
![Screenshot (24)](https://user-images.githubusercontent.com/75713174/193092074-0fc075e0-cc62-40bb-baee-8fc002934dfa.png)

"Community" and "Join Us" collapsing and Website title at left.
![Screenshot (25)](https://user-images.githubusercontent.com/75713174/193092075-e08510e8-7be3-41bf-9025-8b2b31d77e48.png)

x-axis overflow
![Screenshot (26)](https://user-images.githubusercontent.com/75713174/193093129-ad32b9c2-8b69-4a42-914d-ed725abc7a60.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
The website is fully responsive, and also check the website on the mobile 

![image](https://user-images.githubusercontent.com/44284877/193101983-46966a65-571d-40ff-b427-432c5c7a5aab.png)
![image](https://user-images.githubusercontent.com/44284877/193102189-361be83c-b518-47bb-9a36-f257136d15c3.png)

**Comment by sumitbishti** [comment]
As i already mentioned your website has x-axis overflow problem which you can see in the screenshot, plus you navbar's "Join Us" button is intersecting with "Community" link. 
![Screenshot (27)](https://user-images.githubusercontent.com/75713174/193194605-af70dc2d-53f8-4707-a9d4-cc905df25774.png)

![Screenshot (28)](https://user-images.githubusercontent.com/75713174/193195213-0a56c6dd-5a6f-4186-a64a-890905f6f227.png)

**Comment by JhoanAlvear** [comment]
Can I do it? I know React

**Comment by kabir0x23** [comment]
> Can I do it? I know React

Hey
first, analyze the website on your end, and check if is that really a bug or not.
and let us know, we will assign you this issue.

**Comment by JhoanAlvear** [comment]
yes, it is a problem in the navbar and already fix it, only sucede with a certain resolution

**Comment by sumitbishti** [comment]
@kabir0x23  Shouldn't I be the one taking care of it?

**Comment by kabir0x23** [comment]
> yes, it is a problem in the navbar and already fix it, only sucede with a certain resolution

I haven't assigned you this issue yet.
and we haven't decided yet, what to do with this issue.

**Comment by kabir0x23** [comment]
> yes, it is a problem in the navbar and already fix it, only sucede with a certain resolution



> @kabir0x23 Shouldn't I be the one taking care of it?

Hello @sumitbishti 
I have a suggestion.
We can do one thing.
![image](https://user-images.githubusercontent.com/44284877/193314458-16e89897-fd62-4e38-9e5c-ca1a235dbbf3.png)

At this width, start hiding the buttons.
- like at specific width, hide the Twitter button
- and also make sure to keep an eye on the footer too.

if you will have any questions. let us now

If you can do this work, let me know, i will assign you

**Comment by sumitbishti** [comment]
Yes, I can take care of it.

**Comment by kabir0x23** [comment]
> @kabir0x23 Yes, I can take care of it.

Okay, I have assigned this issue to you.
