### ISSUE TITLE
[FEATURE] Jobs/Internships page 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#108]
### Detailed description

For example, what we trying to build:

<img src="https://user-images.githubusercontent.com/44284877/193441392-ea8f3663-e779-492c-b89e-53d627d7f144.png" alt="drawing" width="350"/>

our website link: 
https://www.thecyberhub.org/prep/jobs
http://localhost:3000/prep/jobs

### Context

The jobs page will going to help community members and other users 

### Possible implementation

tech-stack: react and styled-components or CSS

### Additional information

If you need any help or have any doubts, let us know.

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Chitvan14** [comment]
Hi @kabir0x23, I will be happy to make this enhancement, Please assign this issue to me.

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, I will be happy to make this enhancement, Please assign this issue to me.

Will you contribute here first? you will get more green squares too.
-    will you first checkout this repo:
 -   https://github.com/cryptoverseWeb3/git-github-practice

I will assign this issue to you.

**Comment by Chitvan14** [comment]
Okay, I will check the following repo. For information, here more green squares, mean multiple commits?

**Comment by kabir0x23** [comment]
> Okay, I will check the following repo. For information, here more green squares, mean multiple commits?

- yup, more commits, and little practice

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, I will be happy to make this enhancement, Please assign this issue to me.

I have assigned this issue to you.
👨‍💻🚀

**Comment by iyinolu** [comment]
Hi @kabir0x23 I am interested in implementing this feature, Please assign this issue to me.

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 I am interested in implementing this feature, Please assign this issue to me.

Hey, this issue is already got assigned

We have a similar website where you can create this same issue or work on that
https://github.com/cryptoverseWeb3/community.CryptoverseWeb3

**Comment by iyinolu** [comment]
> 

When you say create this same issue, are you trying to add a job/internship page on https://community.cryptoverseweb3.com/ ?

**Comment by kabir0x23** [comment]
> > 
> 
> When you say create this same issue, are you trying to add a job/internship page on https://community.cryptoverseweb3.com/ ?

yes absolutely

**Comment by iyinolu** [comment]
how do i get more information about this issue?

**Comment by kabir0x23** [comment]
> how do i get more information about this issue?

more information?

**Comment by saimaheshtaduri** [comment]
Can I contribute here ?

**Comment by kabir0x23** [comment]
Hello @Chitvan14 
Any progress?
you are working on this issue, right?

**Comment by kabir0x23** [comment]
@iyinolu @saimaheshtaduri 
Any one from is wanted to work on this issue let me know, i will assign you this issue.

Thanks.

**Comment by iyinolu** [comment]
You can assign it to me. Thanks

**Comment by kabir0x23** [comment]
> You can assign it to me. Thanks

Awesome.
assigned.

If will have any doubts, let me know below 😀

**Comment by kabir0x23** [comment]
Hey, @iyinolu Any progress?

If you need any help let me know...

**Comment by abdullmustyy** [comment]
I'd love to work on this @kabir0x23 
Assign it to me, please.

**Comment by kabir0x23** [comment]
@abdullmustyy awesome

Yes i am assigning this issue to you😄🚀

**Comment by abdullmustyy** [comment]
Hi, @kabir0x23 
Here is what I have implemented ⬇️

[New Recording - 10_16_2022, 5_16_23 AM.webm](https://user-images.githubusercontent.com/87391935/196017868-f456e3a6-b9a3-4f9f-b151-d19ac2d404fa.webm)


But I'm still worried about that commits issue. The commits are still showing.
I have tried what you asked. Maybe I'm not doing something right. 😓

**Comment by kabir0x23** [comment]
> Hi, @kabir0x23 
> Here is what I have implemented ⬇️
> 
> [New Recording - 10_16_2022, 5_16_23 AM.webm](https://user-images.githubusercontent.com/87391935/196017868-f456e3a6-b9a3-4f9f-b151-d19ac2d404fa.webm)
> 
> 
> But I'm still worried about that commits issue. The commits are still showing.
> I have tried what you asked. Maybe I'm not doing something right. 😓

Awesome 🤩

This is looking amazing

**Comment by kabir0x23** [comment]
@abdullmustyy once it got completed, send the Pull request, we will see what happens and what to do then
