### ISSUE TITLE
[FEATURE] Simple Website chatbot

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#111]
### Detailed description

When clicking on the chatbot logo 
A window will be open 
example: 
![image](https://user-images.githubusercontent.com/44284877/193454853-2d80517b-3126-4dae-86ae-c6a7427c0c51.png)

---

As in the above image we can see, two options got displayed.
- when a user clicks on a particular option, a specific answer should be displayed over there.

Example:
Option 1: Hello
user clicks on it and got a response: Hello 

Open 2: I need help
after clicking on it, got a response: Hello, how we can help you?

Open 3: Need resources for learning:>
response: Here is your free resources list link. 

### Context

This will be very helpful for everyone

### Possible implementation

If you have any doubts or questions, let us know below

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anjali2201** [comment]
Would like to contribute!

**Comment by kabir0x23** [comment]
> Would like to contribute!

Awesome,
I am assigning you this issue.

If you will have any doubts or questions, you can ask them below.

Thanks.

**Comment by Anjali2201** [comment]
Would not be able to contribute to this, please assign someone else

**Comment by kabir0x23** [comment]
> Would not be able to contribute to this, please assign someone else

@Anjali2201 
Okay, I will assign this to someone else 

Thanks for your time.

**Comment by saimaheshtaduri** [comment]
Can I give it a try ?@kabir0x23

**Comment by kabir0x23** [comment]
> Can I give it a try ?@kabir0x23

Yeah, sure

I am assigning you this issue.

**Comment by kabir0x23** [comment]
Hey @saimaheshtaduri , 
any progress?

If you need any help or have any doubts or questions let us know.

Thank you 😄.

**Comment by kabir0x23** [comment]
If you still want to do this issue, let us know, and we will assign this issue to you.

**Comment by abdullmustyy** [comment]
👋🏻👋🏻👋🏻
So, where will this logo be located?
@kabir0x23

**Comment by kabir0x23** [comment]
> 👋🏻👋🏻👋🏻 So, where will this chatbot logo be located? @kabir0x23

right bottom corner 👾.
and do you have any suggestions?

**Comment by abdullmustyy** [comment]
> > 👋🏻👋🏻👋🏻 So, where will this chatbot logo be located? @kabir0x23
> 
> right bottom corner 👾. and do you have any suggestions?

I mean where on the website, will it be on every page?

Suggestion: 
- We have to identify the purpose of the chatbot.
- Where on the website are users likely to wonder how to go about things?

**Comment by kabir0x23** [comment]
> I mean where on the website, will it be on every page?
> 
> Suggestion:
> 
>     * We have to identify the purpose of the chatbot.
> 
>     * Where on the website are users likely to wonder how to go about things?

Purpose something link FAQ

like when user click on the chat bot
they will get questions, when they click on specific one, they will get the specific ans.

What do you think, 
- should add a faq page or a bot.

**Comment by abdullmustyy** [comment]
> > I mean where on the website, will it be on every page?
> > Suggestion:
> > ```
> > * We have to identify the purpose of the chatbot.
> > 
> > * Where on the website are users likely to wonder how to go about things?
> > ```
> 
> Purpose something link FAQ
> 
> like when user click on the chat bot they will get questions, when they click on specific one, they will get the specific ans.
> 
> What do you think,
> 
> * should add a faq page or a bot.

Having both will be great! 
There will be a separate page for FAQ. 
We just need to find a place on the website where the chatbot will be most effective.

**Comment by kabir0x23** [comment]
> Having both will be great! There will be a separate page for FAQ. We just need to find a place on the website where the chatbot will be most effective.

Nice
I have seen Chatbots are mostly on the right bottom of the screen.

**Comment by kabir0x23** [comment]
Example: 

![image](https://user-images.githubusercontent.com/44284877/196055225-ded70361-7c98-4959-91fe-cd6e675699d5.png)

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 How do I navigate to the "Prep" section? It's no longer in the navbar dropdown.

Hi @abdullmustyy 
Prep section got removed for now. 
You can navigate manually by searching it on the search bar
Will add those categories in learn or somewhere else

thanks

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 

https://user-images.githubusercontent.com/87391935/196994851-f792b3d3-6aff-4932-9db8-c5dc7225c148.mp4

What do you think?

**Comment by abdullmustyy** [comment]
I'm glad you do. 😊
I'll make a PR now.
