### ISSUE TITLE
[FEATURE] Registration from page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#112]
### Detailed description

Registration from the page:
We have to build a similar page like this using react + css or styled-components.
left section got completed, right form section got left.
![image](https://user-images.githubusercontent.com/44284877/193457798-42ebbe41-a39a-4e0d-836d-b766e2f3a14d.png)

### Context

Registration from page will help while registring for accounts or for events.

### Additional information

If you have any questions, let us know below

Thanks.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Alcadeus0** [comment]
Hi I'd like to take this issue up!

**Comment by kabir0x23** [comment]
Awesome
I am assigning this issue to you.

**Comment by iyinolu** [comment]
I'd love to work on this with @Alcadeus0

**Comment by Alcadeus0** [comment]
@iyinolu sure I'd love some help since its quite a task

**Comment by kabir0x23** [comment]
Okay then, i have assign this task to both of you

if u need any help or having questions and doubts, let us know

**Comment by iyinolu** [comment]
great, @Alcadeus0 where can we communicate better. Can I send a message on LinkedIn?

**Comment by Alcadeus0** [comment]
@iyinolu sure let me send a text

**Comment by kabir0x23** [comment]
> great, @Alcadeus0 where can we communicate better. Can I send a message on LinkedIn?

you can talk on discord 
we have open-source chat there too

**Comment by Alcadeus0** [comment]
@kabir0x23 does the page need to be scrolled into view in the homepage or will it be a standalone one?

**Comment by kabir0x23** [comment]
> @kabir0x23 does the page need to be scrolled into view in the homepage or will it be a standalone one?

Hey @Alcadeus0 
This page need to be stand alone

and you can create a registor button at the end of the navbar
once user clicks on the button, that registration page should be displayed.

If you will have any doubts and questions, let me know,

Thanks.

**Comment by Alcadeus0** [comment]
@kabir0x23 thanks for the info. We'll move to the discord server.

**Comment by iyinolu** [comment]
@kabir0x23 can we get the background image on the login screen?

**Comment by iyinolu** [comment]
and perhaps if there is a figma design for it.

**Comment by kabir0x23** [comment]
Hey @iyinolu 
You can use this image.

![CybersecurityRegPage](https://user-images.githubusercontent.com/44284877/193470592-3e735d8b-b4d4-4a4c-9b45-ab2ecfc8c707.png)

**Comment by kabir0x23** [comment]
Hey @Alcadeus0 

That circle with quarter cut for the icon is not required.
If you want to use any icon over there then you can use it.

**Comment by kabir0x23** [comment]
@Alcadeus0 any prgress?
Need any help?

**Comment by jaswindersingh2601** [comment]
Assign this issue to me

**Comment by iyinolu** [comment]
I can complete the entire page, since I started already. @kabir0x23. I have feee time now

**Comment by kabir0x23** [comment]
> I can complete the entire page, since I started already. @kabir0x23. I have feee time now

Awesome
Will asigin this issue to you.

**Comment by kabir0x23** [comment]
> @kabir0x23 I think the codebase is a little bit cluttered. For example we have two Navbar components. How do we address this?

two navbar components?
do you mean, nav and side bar?

**Comment by kabir0x23** [comment]
> > @kabir0x23 I think the codebase is a little bit cluttered. For example we have two Navbar components. How do we address this?
> 
> two navbar components? do you mean, nav and side bar?

or do you mean by inside navabr of reg form?

**Comment by iyinolu** [comment]
there are two components named `NavBar`. The one currently in use does not have the `register` button that takes the user to the register page.

**Comment by iyinolu** [comment]
<img width="305" alt="Screenshot 2022-10-18 at 5 59 46 PM" src="https://user-images.githubusercontent.com/47259302/196497537-b6118847-4029-4a00-8fa4-519127eab56e.png">

Those files both have Navbar components exported

**Comment by kabir0x23** [comment]
okay, homepage navbar componets are old one, when we were having diff navbars for different categoires

**Comment by kabir0x23** [comment]
> <img alt="Screenshot 2022-10-18 at 5 59 46 PM" width="305" src="https://user-images.githubusercontent.com/47259302/196497537-b6118847-4029-4a00-8fa4-519127eab56e.png">
> 
> Those files both have Navbar components exported

now the main navbar is only the separate navbar
![image](https://user-images.githubusercontent.com/44284877/196499540-2ac37561-d5f3-4798-8d5a-b2a0ab28893b.png)

**Comment by kabir0x23** [comment]
your forked repo is too old , fetch and merge it .
![image](https://user-images.githubusercontent.com/44284877/196501599-92b4dffc-ac74-492f-9c50-bb81f82b0894.png)

on our side:
![image](https://user-images.githubusercontent.com/44284877/196501759-33c02ef9-43f1-488e-b6ba-4094f3dcb305.png)

**Comment by iyinolu** [comment]
okay, noted

**Comment by iyinolu** [comment]
<img width="1432" alt="Screenshot 2022-10-21 at 1 15 55 AM" src="https://user-images.githubusercontent.com/47259302/197082707-c386ba21-5dda-4150-b69e-ef8709359a3f.png">
@kabir0x23 Here is what we have now.

**Comment by kabir0x23** [comment]
> <img width="1432" alt="Screenshot 2022-10-21 at 1 15 55 AM" src="https://user-images.githubusercontent.com/47259302/197082707-c386ba21-5dda-4150-b69e-ef8709359a3f.png">
> @kabir0x23 Here is what we have now.

Hey @iyinolu, this is looking awesome ⚡
