### ISSUE TITLE
[FEATURE] Animate components on scroll in homepage

### ISSUE THREAD

**Issue by CreatorLZ** [thecyberworld/thecyberhub.org#113]
### Detailed description

Hi!. I would like to help animate the components in the landing page and give the page a more life like feel. this is in continuity of the precedence already set by the **HeroBg** component.

### Context

this change will improve overall user experience.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by CreatorLZ** [comment]
please kindly assign this issue to me! . thanks !

**Comment by kabir0x23** [comment]
> please kindly assign this issue to me! . thanks !

Hello @CreatorLZ .
- Can you elaborate more, like what you want to do exactly?

**Comment by CreatorLZ** [comment]
[https://creatorlz.github.io/Huddle/](Something like this). Observe the behaviour of the components with descriptions 
![IMG_20221002_181550](https://user-images.githubusercontent.com/99528764/193467177-0e8ee7d2-2c99-4346-a925-525f7ecaaa5c.jpg)

**Comment by CreatorLZ** [comment]
Hi kabir0x23 should I close this issue ?

**Comment by kabir0x23** [comment]
Hey @CreatorLZ I am closing this issue.

You can create something like issue or features requests

Thanks.
