### ISSUE TITLE
[BUG] Want to add an Hover effect on anchor links.

### ISSUE THREAD

**Issue by KiranAminPanjwani** [thecyberworld/thecyberhub.org#115]
### Describe the bug

The Overall website is awesome! 💚
But I have noticed that the "Contribute" and "Join" has no hover effect in the "About Thecyberworld" section.
Similarly, the same goes with the "Resources" drop-down menu.

### To Reproduce

I want to add a hover effect to the "Contribute" and "Join" text which will make it easier for the user to navigate.
I also want to add hover effects on the "Resources" dropdown menu links.

I am a Hacktoberfest participant, @kabir0x23  please assign this issue to me. 😊

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/90326051/193468370-03018f70-621f-49b9-9735-d448dcd428d2.png)

![image](https://user-images.githubusercontent.com/90326051/193466040-efab9b7a-5979-4b58-b9a6-a3aebb0018ee.png)

![image](https://user-images.githubusercontent.com/90326051/193466022-03cd2927-4136-4aa0-9bed-7401c2eb2c92.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by lordashuchauhan** [comment]
Hey! is this issue under Hacktoberfest 2022?
If yes I would like to work on this.

**Comment by kabir0x23** [comment]
> Hey! is this issue under Hacktoberfest 2022? If yes I would like to work on this.

Nope, hovering something shouldn't be in hacktoberfest.
You can check other issues as well.

**Comment by kabir0x23** [comment]
Hey @KiranAminPanjwani 
This is not any type of bug, we made this intentionally.

We are restructuring our community website, and we have created many issues, must give a look.
if you need more issues, then you can check out my profile, I have mentioned 10+ open-source projects
