### ISSUE TITLE
[FEATURE] Single page Blogs 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#116]
### Detailed description

This feature is about:
- we have a blog page -> 
- we want, when someone clicks on the blog, it's content should be displayed on the screen.
- For example hashcode, medium 

### Context

![image](https://user-images.githubusercontent.com/44284877/193466713-2dfde12a-52e0-42c6-8814-51a32f21beb4.png)
- links:
  - https://www.thecyberhub.org/resources/blogs
  - http://localhost:3000/resources/blogs

### Possible implementation

you can use dummy data right now
we will add the database after this task got completed.
use this data: https://kabir0x23.hashnode.dev/what-is-docker

### Additional information

If you need any help, any doubts , let us know below.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritroCoder** [comment]
You can assign this issue to me now

**Comment by aritroCoder** [comment]
[Screencast from 03-10-22 10:33:18 AM IST.webm](https://user-images.githubusercontent.com/92646038/193504920-b71cae28-01c5-41dc-956e-f8db11d10d11.webm)
I have added this blog page, please comment if it is okay

**Comment by kabir0x23** [comment]
> [Screencast from 03-10-22 10:33:18 AM IST.webm](https://user-images.githubusercontent.com/92646038/193504920-b71cae28-01c5-41dc-956e-f8db11d10d11.webm) I have added this blog page, please comment if it is okay

Cool, looks good

**Comment by aritroCoder** [comment]
I have made the PR
