### ISSUE TITLE
[FEATURE] Navbar: new dropdown navbar

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#117]
### What would you like to share?

I have a new issue, will create it.

---
At homepage:

![image](https://user-images.githubusercontent.com/44284877/193499082-1f1a1ca3-6e1f-4144-8053-c1225f297cd5.png)

when we click on community, it will go down by smooth scroll

We want to use the same navbar on every page, (the same navbar is currently on my local machine,.)
so when we are on a different page.

![image](https://user-images.githubusercontent.com/44284877/193499262-aaa2a772-ed67-4981-86a8-cc7cf8ab1d83.png)
if we click on community, can we go back and smooth-scroll to the community section?
how we can accomplish that

If not possible, we will change the structure then.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by saimaheshtaduri** [comment]
@kabir0x23 I think we can, not sure though. Assign the task to me. I will work on it and update you.

**Comment by kabir0x23** [comment]
> @kabir0x23 I think we can, not sure though. Assign the task to me. I will work on it and update you.

Let's discuss first

**Comment by kabir0x23** [comment]
> @kabir0x23 I think we can, not sure though. Assign the task to me. I will work on it and update you.

I have an idea
like in every section we have button now.okay 
so we can add a downicon-button, when user clicks on that, that will navitgate them below

**Comment by saimaheshtaduri** [comment]
I have another idea.  
we can add a `<Link to"/"> ` to homepage in the nav bar, so that at first homepage opens up and scrolls to corresponding section. 

I think this works. Is this oky for you ?

**Comment by saimaheshtaduri** [comment]
can you push your changes to a new branch may be, so that I can work on it. Thanks @kabir0x23

**Comment by kabir0x23** [comment]
> can you push your changes to a new branch may be, so that I can work on it. Thanks @kabir0x23

okay, I am creating a new, branch

**Comment by kabir0x23** [comment]
> can you push your changes to a new branch may be, so that I can work on it. Thanks @kabir0x23

here is the branch, i have pushed the code here
https://github.com/thecyberworld/thecyberhub.org/tree/fix-navbar-design

**Comment by kabir0x23** [comment]
I have a new design. i am sharing it , and will make different issues

**Comment by saimaheshtaduri** [comment]
@kabir0x23  any updates regarding navbar ?

**Comment by kabir0x23** [comment]
> @kabir0x23 any updates regarding navbar?

Yes, we will create new issues by today, in some minutes 

Thanks.

**Comment by saimaheshtaduri** [comment]
@kabir0x23 if possible let me know once you raise an issue, I can contribute.
Thanks !

**Comment by kabir0x23** [comment]
> @kabir0x23 if possible let me know once you raise an issue, I can contribute. Thanks !

@saimaheshtaduri 
I have raised an feature request before 



It;s just simple chatbot
must give a look #111 

sure i will tag you once the issues got raised 

Thank you.

**Comment by kabir0x23** [comment]
@saimaheshtaduri 

![image](https://user-images.githubusercontent.com/44284877/194759372-cab3c49a-55ca-47db-87d5-5e08bf04bafe.png)

Like we are working on dropdowns, like two separate dropdowns. like shown in the above image.

want to work on this issue?

**Comment by saimaheshtaduri** [comment]
Yes! I will. Assign to me @kabir0x23

**Comment by kabir0x23** [comment]
> Yes! I will. Assign to me @kabir0x23

Awesome

**Comment by kabir0x23** [comment]
Suggestions:
- Learn:
  - Roadmap
  - Courses
  - blogs 
- we can remove the side dropdown:
  - Prep
- under the resources section:
  - quiz  
  - Interview Questions
  - jobs
  - news
  - \+ \+

**Comment by kabir0x23** [comment]
@saimaheshtaduri there is event going on, just have to do simple contributions like we are doing 
just have to register overself over there, something like hacktoberfest
but have to do in team 
if you want to join , let me know.

Thanks

**Comment by saimaheshtaduri** [comment]
Cool. What is it ?

**Comment by kabir0x23** [comment]
> Cool. What is it ?

are you on our discord server?

**Comment by kabir0x23** [comment]
![image](https://user-images.githubusercontent.com/44284877/194764657-f54db5ad-9712-4009-9c84-bcfff72f980e.png)

**Comment by kabir0x23** [comment]
https://www.hacksquad.dev/

**Comment by saimaheshtaduri** [comment]
yeah! I am already doing this @kabir0x23  :)

**Comment by kabir0x23** [comment]
> yeah! I am already doing this @kabir0x23 :)

awsome, are you in a team?
rank number?

**Comment by saimaheshtaduri** [comment]
1st position as of now :)

**Comment by kabir0x23** [comment]
> 1st position as of now :) 

Ahn, cool
30, coz right now I am a solo player.

**Comment by saimaheshtaduri** [comment]
still its great 👍

**Comment by M-Rahul1** [comment]
> still its great 👍

Nice re @saimaheshtaduri 😂 . Tho I joined his team with low contribution

**Comment by kabir0x23** [comment]
Hey @saimaheshtaduri , 
any progress?

If you need any help or have any doubts or questions let us know.

Thank you 😄.

**Comment by kabir0x23** [comment]
If you still want to do this issue, let us know, and we will assign this issue to you.
