### ISSUE TITLE
[FEATURE] Community page (separate page)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#121]
### Detailed description

We have to build a community page.

- A little bit about community 
- Discord link
- Twitter about our community

### Context

The community page will help user to know more about the community 
and will be able to join the community through the community page.

### Possible implementation

Example page: 
![image](https://user-images.githubusercontent.com/44284877/193537160-f08f8358-3fe9-4356-a059-4bf98176e092.png)

### Additional information

If you need any help or have any doubts, can ask below.
Thanks

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by akshitarora921** [comment]
@kabir0x23, Can I take this?

**Comment by kabir0x23** [comment]
> @kabir0x23, Can I take this?

Hello @akshitarora921,
I am assigning you this issue

**Comment by abdullmustyy** [comment]
Hi, @kabir0x23 

I see this issue has no assignee, and I'd love to work on it.
Assign it to me, please.

**Comment by abdullmustyy** [comment]
Question: Where do I the image/video for the background, and also the testimonials?

**Comment by kabir0x23** [comment]
> Hi, @kabir0x23
> 
> I see this issue has no assignee, and I'd love to work on it. Assign it to me, please.

awesome, i am assigning it to you.

**Comment by kabir0x23** [comment]
> Question: Where do I the image/video for the background, and also the testimonials?

you can leave the testimonials for now

the center section would be greate for now.

If you will have any questions, let us know.

Thank you.

**Comment by abdullmustyy** [comment]
Alright, I'll need the background image and the discord channel link.

**Comment by kabir0x23** [comment]
> Alright, I'll need the background image and the discord channel link.


discord link you can take from the footer.
image:  

![community_background](https://user-images.githubusercontent.com/44284877/194478554-8dd5ae26-1f61-4a29-a451-9f00822b5188.png)

**Comment by abdullmustyy** [comment]
Alright, thank you. 
I'm on it.

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 
Is this okay?

![Screenshot (7)](https://user-images.githubusercontent.com/87391935/194622502-51354e6b-9d5a-4a40-976b-5b375639ef73.png)

**Comment by kabir0x23** [comment]
> Hi @kabir0x23 Is this okay?
> 
> ![Screenshot (7)](https://user-images.githubusercontent.com/87391935/194622502-51354e6b-9d5a-4a40-976b-5b375639ef73.png)

okay?
It's just Awesome

**Comment by kabir0x23** [comment]
can you do one change?

discord color: papule 
green looks good. but the thing is discord is purple will look different
What do you think?

**Comment by kabir0x23** [comment]
green looks good too

**Comment by abdullmustyy** [comment]
> can you do one change?
> 
> discord color: papule green looks good. but the thing is discord is purple will look different What do you think?

Hmmm, I'll do that now. Thank you.
So, what next?

**Comment by abdullmustyy** [comment]
Hmmm, not bad.

![Screenshot (8)](https://user-images.githubusercontent.com/87391935/194625189-d6ea1fa7-b263-4a7d-b0b1-b5fc42ad4abc.png)

**Comment by kabir0x23** [comment]
> Hmmm, not bad.
> 
> ![Screenshot (8)](https://user-images.githubusercontent.com/87391935/194625189-d6ea1fa7-b263-4a7d-b0b1-b5fc42ad4abc.png)

Awesome
I think You can make a PR now

**Comment by abdullmustyy** [comment]
> > Hmmm, not bad.
> > ![Screenshot (8)](https://user-images.githubusercontent.com/87391935/194625189-d6ea1fa7-b263-4a7d-b0b1-b5fc42ad4abc.png)
> 
> Awesome I think You can make a PR now

Okay, I'll do that now.
Thank you.

**Comment by kabir0x23** [comment]
> > > Hmmm, not bad.
> > > ![Screenshot (8)](https://user-images.githubusercontent.com/87391935/194625189-d6ea1fa7-b263-4a7d-b0b1-b5fc42ad4abc.png)
> > 
> > 
> > Awesome I think You can make a PR now
> 
> Okay, I'll do that now. Thank you.

thanks for the contribution. 😄

**Comment by abdullmustyy** [comment]
> > Okay, I'll do that now. Thank you.
> 
> thanks for the contribution. 😄

Thank you @kabir0x23 

I'm so sorry. I got carried away and ran "git add ." 
I hope it won't be a problem. I promise it won't happen again.

**Comment by kabir0x23** [comment]
> Thank you @kabir0x23
> 
> I'm so sorry. I got carried away and ran "git add ." I hope it won't be a problem. I promise it won't happen again.

It's okay, don't need to say sorry, it happens.
I will make changes from my side if some unwanted files got committed.

**Comment by abdullmustyy** [comment]
> > Thank you @kabir0x23
> > I'm so sorry. I got carried away and ran "git add ." I hope it won't be a problem. I promise it won't happen again.
> 
> It's okay, don't need to say sorry, it happens. I will make changes from my side if some unwanted files got committed.

Alright, thank you so much.

I've just made a PR, please review it.
