### ISSUE TITLE
[BUG] Sidebar 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#128]
### Describe the bug

When we click on the sidebar-nav item, it automatically closes the sidebar and opens the new page.
whereas when we click on the dropdown nav-items, it doen;t close the sidebar automatically
under Learn navitem:
- navitem > learn
- navitem > learn > prep

<img src="https://user-images.githubusercontent.com/44284877/194046321-07e9b714-84e0-4c89-9c16-57a022e0874d.png" alt="drawing" width="200"/>
### To Reproduce

- navitem > events:
  - works.
- navitem > learn > prep > quiz:
  - does not work.

### Expected Behavior

When we click on:
- navitem > learn > prep > quiz:

it should work the same as events and blogs.

### Screenshot/ Video

screenshot: 
<img src="https://user-images.githubusercontent.com/44284877/194046321-07e9b714-84e0-4c89-9c16-57a022e0874d.png" alt="drawing" width="200"/>

video:

https://user-images.githubusercontent.com/44284877/194047248-01af7233-7c4f-4140-9415-c4b791eef504.mp4

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
@saimaheshtaduri this was working fine before when we are having different navbars and when we were on the homepage.
but now as we have only the same bar. now sidebar is not getting toggle.

**Comment by saimaheshtaduri** [comment]
I will work on this. Please assign me @kabir0x23

**Comment by kabir0x23** [comment]
Awesome, assigned 🚀

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 
I'm back, and I've resolved this bug! 😃

https://user-images.githubusercontent.com/87391935/195222717-3708fc12-d8d9-42fd-8674-e6646f26d95a.mp4

What do you think?

**Comment by kabir0x23** [comment]
Nice @abdullmustyy 
Looking good

**Comment by abdullmustyy** [comment]
Good morning @kabir0x23 
I have just made a PR, please review it.
