### ISSUE TITLE
[FEATURE] Add single Event page (like blog)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#129]
### Detailed description

We have this Events page.
<img src="https://user-images.githubusercontent.com/44284877/194047980-850511f0-658e-47c0-adc8-51bae968f957.png" alt="drawing" width="100%"/>

When someone clicks on the events, particular details should be open according to the event id

when the user clicks on event-1, the details of event-1 should be open.

### Context

This will help users to know more about events.

### Possible implementation

we already have implemented this with blogs
now we have to make events dynamic.

you can check out the source code of blogs

### Additional information

If you need any help or have doubts, let us know.

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hello @aritroCoder 
If you want to do.. Let us know

Thank you.

**Comment by RahulSharma4329** [comment]
Hey @kabir0x23 I would like to work on this issue can you assign this to me

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 I would like to work on this issue can you assign this to me 

Yes sure

I am assigning this issue to you.

**Comment by RahulSharma4329** [comment]
Can you please tell me how the new events are added to the the page ? Is it hard coded into the page ?

**Comment by kabir0x23** [comment]
> Can you please tell me how the new events are added to the the page ? Is it hard coded into the page ?

events details are in the data filr

**Comment by kabir0x23** [comment]
> Can you please tell me how the new events are added to the the page ? Is it hard coded into the page ?

If you need any help or having any doubts, let us know.

**Comment by kabir0x23** [comment]
Hey @RahulSharma4329 , 
any progress?

If you need any help or have any doubts or questions let us know.

Thank you 😄.

**Comment by kabir0x23** [comment]
If you still want to do this issue, let us know, and we will assign this issue to you.

**Comment by jaswindersingh2601** [comment]
Assign this issue to me

**Comment by kabir0x23** [comment]
> Assign this issue to me

It's been 8 days,
I will work on this issue

**Comment by nirajpdn** [comment]
@kabir0x23 any progress ? I would like to work on this issue.

**Comment by kabir0x23** [comment]
> @kabir0x23 any progress ? I would like to work on this issue.

Yes sure, i have done the navigation and page part,
the issues is, it is not navigating to the absolute path.
