### ISSUE TITLE
[BUG] [FEATURE] Quiz categories are overflowing 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#130]
### Describe the bug

Quiz categories are overflowing.

Example: 
<img alt="drawing" width="1000" src="https://user-images.githubusercontent.com/44284877/194101381-2f2c2aea-df0f-4d8d-b6fd-4692eecf9176.png">

we can make a dropdown, when we click on the dropdown, only then categories should be visible to use.

### To Reproduce

If you need any help or have any doubts, let us know

Thank you

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by andreaevolo** [comment]
Are you refering to the categories to the right? I would like to solve this issue.

**Comment by kabir0x23** [comment]
> Are you referring to the categories to the right? I would like to solve this issue.

We want a dropdown, when we click on that button, then categories should be displayed by a dropdown.
Example:
![image](https://user-images.githubusercontent.com/44284877/194109496-83d890cb-01c9-4791-880a-9a37b2bb243d.png)

If you have any doubts let me know.

**Comment by kabir0x23** [comment]
> It's not clear to me where the dropdown with the categories should be displayed. Do I need to display them when the user click learn > prep > quiz? And what about the categories displayed on top of the questions? Can I fix the overflowing issue on smaller screens?

Okay, you can fix the overflowing issue

**Comment by andreaevolo** [comment]
![contrib-mobile](https://user-images.githubusercontent.com/37835057/194118395-10e3477a-df63-4e45-abee-5aa75701c4d1.PNG)
![contrib-desktop](https://user-images.githubusercontent.com/37835057/194118410-df6ec889-057a-4bf1-9890-1751acb06c2b.PNG)
I've made this changes, but I would olso need to modify the CBQ component to adjast the layout on mobile.

**Comment by kabir0x23** [comment]
See
![image](https://user-images.githubusercontent.com/44284877/194120395-2cbfebeb-28c7-4f54-a2d2-b550fac3a1ae.png)
![image](https://user-images.githubusercontent.com/44284877/194120448-880c6fa4-c190-45e1-8e09-4db44f1d16ba.png)

i was talking about this

**Comment by andreaevolo** [comment]
Okay later I'll work on that. Can I keep the changes I've already made?

**Comment by kabir0x23** [comment]
> Okay later I'll work on that. Can I keep the changes I've already made?

yes..

**Comment by kabir0x23** [comment]
you can just add a dropdown in this
![image](https://user-images.githubusercontent.com/44284877/194125764-299b867f-7e20-454c-8087-62f8428d5a18.png)

**Comment by andreaevolo** [comment]
So thinking of building a new component, the description of the dropdown will be visible when hovering the button, when it is clicked it will show all the other quizzes links. What do you think?

**Comment by kabir0x23** [comment]
> So thinking of building a new component, the description of the dropdown will be visible when hovering the button, when it is clicked it will show all the other quizzes links. What do you think? @kabir0x23

Yes, great

**Comment by kabir0x23** [comment]
@andreaevolo Any progress mate?
If you need any help let me know...

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 
What's good? So, I decided to finish what I started with this contribution. 

I have implemented the dropdown you requested, and I'm adding some finishing touches. I'll send images in a minute.

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 

![Screenshot (10)](https://user-images.githubusercontent.com/87391935/194708520-a05d1f3f-06f4-4670-9301-3a3f0a44f7a0.png)

![Screenshot (11)](https://user-images.githubusercontent.com/87391935/194708523-eff4d31d-ed8d-486a-80b9-829531e50c7d.png)

![Screenshot (12)](https://user-images.githubusercontent.com/87391935/194708525-646b9b9f-97c8-4a62-b2ce-201a08b70395.png)

![Screenshot (15)](https://user-images.githubusercontent.com/87391935/194708526-4fc25c8c-3567-43f5-94b3-626b74e25a9e.png)

**Comment by abdullmustyy** [comment]
> Hi @kabir0x23
> 
> ![Screenshot (10)](https://user-images.githubusercontent.com/87391935/194708520-a05d1f3f-06f4-4670-9301-3a3f0a44f7a0.png)
> 
> ![Screenshot (11)](https://user-images.githubusercontent.com/87391935/194708523-eff4d31d-ed8d-486a-80b9-829531e50c7d.png)
> 
> ![Screenshot (12)](https://user-images.githubusercontent.com/87391935/194708525-646b9b9f-97c8-4a62-b2ce-201a08b70395.png)
> 
> ![Screenshot (15)](https://user-images.githubusercontent.com/87391935/194708526-4fc25c8c-3567-43f5-94b3-626b74e25a9e.png)

What do you think?

**Comment by kabir0x23** [comment]
Awesome.

looking good.

**Comment by abdullmustyy** [comment]
@kabir0x23 
I just made a PR, please review it.
Thank you.

**Comment by abdullmustyy** [comment]
> @kabir0x23 I just made a PR, please review it. Thank you.

@kabir0x23
