### ISSUE TITLE
[FEATURE] Create About section

### ISSUE THREAD

**Issue by ShorunTech** [thecyberworld/thecyberhub.org#135]
### Detailed description

If you click on the About Tab you will only see About without fully details.
but there is About Section on the page, is just to link the About tab to the section on page.

### Context

-- Give new visitor a brief of what the website is all about
-- click on the About Tab to link to the section
-- Help others to easily navigate

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ShorunTech** [comment]
I can work on it, If assign to me.

**Comment by kabir0x23** [comment]
> I can work on it, If assign to me.

Yes sure, we have create the content of the about section.

**Comment by ShorunTech** [comment]
working on it

**Comment by kabir0x23** [comment]
> working on it

okay, nice

If you will need any help or have any questions or doubts let us know below.
Thank you.

**Comment by kabir0x23** [comment]
@ShorunTech working on this?

Hey @ShorunTech , 
any progreess?

If you need any help or have any doubts or questions let us know.

Thank you 😄.

**Comment by ShorunTech** [comment]
concerning  the About section what are the likely features you are looking forward to.
or should i use this template for the about section.

![Screenshot (199)](https://user-images.githubusercontent.com/61280687/195834338-009de1c7-eb4f-448e-84c9-b1882d8d3b06.png)

**Comment by kabir0x23** [comment]
> 

yes, i think there is no need for a same section on the navbar.
we already have this on homepage so..
