### ISSUE TITLE
[BUG] Overflowing the blogs (not responsive)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#142]
### Describe the bug

Overflowing the blogs section:
- not responsive in blogs 

Blogs section:
- overflowing the sides in the blog section:
- <img src="https://user-images.githubusercontent.com/44284877/194499407-65a054a0-692a-437b-ba3c-784ca854a46d.png" alt="image" width="200"/>

Event section:
- working fine in events (similar design and code)
- <img src="https://user-images.githubusercontent.com/44284877/194500172-40e576cb-b695-48e3-bcb5-3c9a5b5a4cb1.png" alt="image" width="200"/>

### To Reproduce

Website: https://www.thecyberhub.org/events
Localhost: http://localhost:3000/blogs

### Screenshot/ Video

<img src="https://user-images.githubusercontent.com/44284877/194499407-65a054a0-692a-437b-ba3c-784ca854a46d.png" alt="image" width="200"/>

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by indiehjaerta** [comment]
Hello @kabir0x23 I would like to try this as my first issue ever

**Comment by kabir0x23** [comment]
Hello @indiehjaerta 

Sure, I am assigning you this issue.
