### ISSUE TITLE
[BUG] Blogs are not responsive

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#143]
### Describe the bug

Blogs are not responsive

View blog:
- On mobile:
  - <img src="https://user-images.githubusercontent.com/44284877/194500962-b14f541b-2881-4c0c-bec6-304f090012ea.png" alt="image" width="200"/>
- On Desktop:
  - <img src="https://user-images.githubusercontent.com/44284877/194501207-adae52e9-35db-44a2-90a7-0f909c3903dc.png" alt="image" width="200"/>
 

### To Reproduce

local: http://localhost:3000/blogs/viewBlog?id=1

website: http://thecyberhub.org/blogs/viewBlog?id=1

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by abitsalihu** [comment]
Hey @kabir0x23, I would like to help with this issue. :)

**Comment by kabir0x23** [comment]
Awesome

I have assigned this issue to you.
