### ISSUE TITLE
[FEATURE] Change in URL structure of blogs

### ISSUE THREAD

**Issue by A-Spiral-Forge** [thecyberworld/thecyberhub.org#155]
### Detailed description

Currently the blog URL are displayed like this:
```
https://www.thecyberhub.org/blogs/viewBlog?id=1
```
I think if we display the URL in below format it will be much better. New format:
```
https://www.thecyberhub.org/blogs/viewBlog/What-is-Docker
````

### Context

I think this is important because we can go to the blog directly through URL by typing title of the blog. 
It also looks nicer then using querying parameters.

### Possible implementation

Just by changing a little code of routing in viewBlogs.jsx file.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by A-Spiral-Forge** [comment]
@kabir0x23 If you consider this please assign it to me.

**Comment by kabir0x23** [comment]
Awesome,

Sure I am assigning this issue to you.
