### ISSUE TITLE
[FEATURE] Blog card component UI

### ISSUE THREAD

**Issue by ziarparvaiz** [thecyberworld/thecyberhub.org#158]
### Detailed description

I can make the blog card (Blogs Elements) component a little more stylish it will look nicer and with tag buttons.

![Screenshot 2022-10-09 at 02-03-07 Cyber Security Made Easy](https://user-images.githubusercontent.com/50423368/194730637-b815d7c4-8a72-439d-a60a-10f019e73e15.png)

### Context

This will make your website UI better.

### Possible implementation

Hover border color on the card style like img effect

### Additional information

please assign me to do this issue.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Okay, I am assigning you this issue.
