### ISSUE TITLE
Blog data (blog details) are not responsive on mobile

### ISSUE THREAD

**Issue by sanketshevare** [thecyberworld/thecyberhub.org#159]
### Detailed description

Blog details are not responsive can i eork on this?

### Context

All text shows in the middle of screen and user will not read it properly from small devices

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

![Screenshot_2022-10-09-19-34-12-77.jpg](https://user-images.githubusercontent.com/69853783/194761232-a0a1d46f-7b7b-46ff-8d0f-7efa25e5ab26.jpg)

**Comment by kabir0x23** [comment]
Duplicate #143

**Comment by kabir0x23** [comment]
Thanks for creating this issues, This blog issues is already got mentioned in issues and already has been assigned
