### ISSUE TITLE
[FEATURE] Create Certifications with unique id with users details (example udemy certs)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#160]
### Detailed description

Example: In udemy or anywhere, we got our certification on the behalf of the details we have submitted before.
so we want to build a page, where we provide users with details and got a certification with unique id with the link
so they also can share those with others

### Context

We used to do CTFs (cyber security competitions) for free for the community with prizes
and we also want to provide certifications of winning and participations.

### Additional information

If you will have any doubts or questions let un know below:

Thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Im-Kunal-13** [comment]
@kabir0x23 I would like to work on this. Can you assign this to me?

**Comment by kabir0x23** [comment]
> @kabir0x23 I would like to work on this. Can you assign this to me?

Awesome,

I am assigning this issue to you.

**Comment by Im-Kunal-13** [comment]
@kabir0x23 On it

**Comment by sameer1612** [comment]
@kabir0x23 
I can take this one. Worked on building a European certification system a few years back.

**Comment by kabir0x23** [comment]
> @kabir0x23 I can take this one. Worked on building a European certification system a few years back.

Hey @sameer1612 
will that feature will be working on a static website? or need to connect data base for proper working? 
(we know data base i important, and we are working on that, will gonna add it soon.)

**Comment by sameer1612** [comment]
> > @kabir0x23 I can take this one. Worked on building a European certification system a few years back.
> 
> 
> 
> Hey @sameer1612 
> 
> will that feature will be working on a static website? or need to connect database for proper working? 
> 
> (we know data base is important, and we are working on that, will gonna add it soon.)


Hey @kabir0x23 
You don't need a full scale database. A simple cloud function with a firebase db should be enough. It will have only 2 responsibilities, to validate a certificate id and create one(not public). It's hardly an hour's work in setup.

**Comment by sameer1612** [comment]
@kabir0x23 you can schedule a google calendar meet at cyber726337@gmail.com between 6-8pm tomorrow if you want me to implement this. Thanks!

**Comment by kabir0x23** [comment]
> @kabir0x23 you can schedule a google calendar meet at [cyber726337@gmail.com](mailto:cyber726337@gmail.com) between 6-8pm tomorrow if you want me to implement this. Thanks!

Awesome, we can do it at 7 pm
and I am just trying this thing, and I have scheduled the meet

Thanks
