### ISSUE TITLE
[FEATURE] Add button link to Open-Source project page

### ISSUE THREAD

**Issue by abdullmustyy** [thecyberworld/thecyberhub.org#174]
### Detailed description

Add a button link to the Community section. Clicking on this button takes you to the Open-Source projects page.

### Context

The Community section summarizes how important it is to make Open-Source contributions. So, I believe that providing a way for users to get to the available Open-Source projects in that section would be great.

### Possible implementation

[New Recording - 10_13_2022, 2_32_23 PM.webm](https://user-images.githubusercontent.com/87391935/195630340-15fc2120-626d-43e4-9030-3afe88db1658.webm)

### Additional information

Nil

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey @abdullmustyy , I have merged that pr, now you can work on that.

Thanks.
