### ISSUE TITLE
[FEATURE] Build a simple static submission page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#180]
### Detailed description

Build a simple static page submission page under Play CTF.

### Context

The value stored in the backend: is 193471289037
If a user submits the value 193471289037, turn the button green. and display congrats.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by tanyaa-arora** [comment]
Hi @kabir0x23, I'd like to work on the issue. Kindly assign it to me

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, I'd like to work on the issue. Kindly assign it to me

Sure, I am assigning this issue to you.

**Comment by kabir0x23** [comment]
this issue is very simple, like login page nothing else.

If you still want to do, or having any doubts, let us now

**Comment by tanyaa-arora** [comment]
@kabir0x23 okay, I'll try it again. Actually, I was having issue with it's css. My page was overlapping with the header and navbar component.

**Comment by kabir0x23** [comment]
> @kabir0x23 okay, I'll try it again. Actually, I was having issue with it's css. My page was overlapping with the header and navbar components.

Awesome.
the solution to the CSS: 
- just give a 200px margin-top to the main container, then it will be fine.

If you will have any doubts or questions let us know.
Thank you.

**Comment by tanyaa-arora** [comment]
I wanted to know if the user will be redirected to submit page when he clicks on play CTF. That's what our plan is, right?

**Comment by kabir0x23** [comment]
> I wanted to know if the user will be redirected to submit page when he clicks on play CTF. That's what our plan is, right?

yes, right 👍

**Comment by tanyaa-arora** [comment]
I'm not able to route to the submit page, If you could guide me with that

**Comment by pratyushkr11** [comment]
Hello @kabir0x23 can u please assign me this issue. I would like to work on this

**Comment by kabir0x23** [comment]
> I'm not able to route to the submit page, If you could guide me with that



> I'm not able to route to the submit page, If you could guide me with that

you can directly work on this page: https://www.thecyberhub.org/CTF
or 

routing, you have to add routing in the app. jsx like this: 

![image](https://user-images.githubusercontent.com/44284877/196035292-a8e0b6cc-cec3-4ba5-bab7-5d3395b7ec64.png)

**Comment by tanyaa-arora** [comment]
Okay👍

**Comment by abdullmustyy** [comment]
@kabir0x23 
👁️👁️

**Comment by abdullmustyy** [comment]
Hi @kabir0x23 
Is someone working on this already?

**Comment by kabir0x23** [comment]
my bad 😅
your one is here https://github.com/thecyberworld/thecyberhub.org/issues/111
