### ISSUE TITLE
[FEATURE] Convert Blogs css files  into styled components 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#183]
### Detailed description

Convert Blogs css files  into styled components 

### Context

Change the  BlogsElements.jsx into BlogsCard.jsx
and convert css file into styled into BlogsElements.jsx

![image](https://user-images.githubusercontent.com/44284877/195972596-efe081c3-f514-4b8b-8944-d5bc7020d824.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by amardeep911** [comment]
plz assignt this to me

**Comment by kabir0x23** [comment]
> plz assignt this to me

Awesome.

I am assigning this issue to you.

**Comment by amardeep911** [comment]
You want to use styled.module.css?

**Comment by kabir0x23** [comment]
> You want to use styled.module.css?

We are already using CSS styled-components in our project
like this. 

![image](https://user-images.githubusercontent.com/44284877/195972953-960e5d07-512e-4901-856e-85eedcdce951.png)


We want to convert
this blogs.css file into 
![image](https://user-images.githubusercontent.com/44284877/195972982-be5244ed-b1c1-4f3a-9e23-547a2db1d571.png)

styled structure.

got it?

If you will have any doubts, let us know

**Comment by amardeep911** [comment]
Yeah Got it thanks

**Comment by amardeep911** [comment]
Also how to run the code npm start is not worrking

**Comment by sameer1612** [comment]
@kabir0x23 migrated the blog and certificate to styled-components. Please review when available.
