### ISSUE TITLE
[BUG] Non-responsive Events page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#185]
### Describe the bug

1. widescreen issues
 ![image](https://user-images.githubusercontent.com/44284877/195988003-9ddc9ee4-bddc-4198-948e-a9e049cec8b1.png)

2. Past events section should be aligned right to Today's Events

### To Reproduce

website: https://www.thecyberhub.org/events

localhost: http://localhost:3000/events

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by nirajpdn** [comment]
I want to work on this. Assign it to me.

**Comment by kabir0x23** [comment]
Awesome, I am assigning this issue to you.
