### ISSUE TITLE
[BUG] Logic issue in Events 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#186]
### Describe the bug

Logic issues in order

![image](https://user-images.githubusercontent.com/44284877/195988178-2ae8b0b6-2f8a-4c8d-91fc-596c287787e4.png)

1. Top section is today's events: date 15. ✔
2. upcoming is also containing past events dates of data ❌
3. past events: is containing only single events, should be more past events ❌

### To Reproduce

localhost: http://localhost:3000/events
website: https://www.thecyberhub.org/events

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Ruchita-01** [comment]
Issue Resolved 
Kindly Check Below PR
https://github.com/thecyberworld/thecyberhub.org/pull/191
