### ISSUE TITLE
[FEATURE] Design Improvement of Quiz Section

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#189]
### Detailed description

Design Improvement of Quiz Section

### Context

![image](https://user-images.githubusercontent.com/44284877/195989969-ff20065f-52dc-4b2a-9b3c-dbbcda6aa317.png)

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by DhavalDobariya333** [comment]
Hi @kabir0x23,  can you let me know where is quiz section on the website is?

**Comment by kabir0x23** [comment]
> Hi @kabir0x23, can you let me know where is quiz section on the website is? So I can look at it.

hi @DhavalDobariya333 

you can find quiz under: learn > prep > quiz

**Comment by DhavalDobariya333** [comment]
Hi @kabir0x23, can I do this issue?

**Comment by kabir0x23** [comment]
sure

**Comment by jahtomini** [comment]
Hey @kabir0x23!  I'll like to work on this issue

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 I'll like to work on this issue but I need to clarify something first. Is this a design + code implementation, meaning I come up with a new design and turn it into code?

Hey @jahtomini 
Yes, we have to improve the design (layout design)

one of the example
buttons width and the quiz section width are miss match, so this is looking wierd
![image](https://user-images.githubusercontent.com/44284877/197778797-aa38ec10-de48-4620-9853-ab4f4ab01ac4.png)

**Comment by kabir0x23** [comment]
> Oh I see, I came up with a redesign with further tweaks to the UI, let me know what you think ![thecyberhubdotorg_quiz_redesign](https://user-images.githubusercontent.com/93228906/197836285-81965c62-1f20-4fdd-9c5b-db969ebfe19c.png)

Nice, better
