### ISSUE TITLE
Upcomming events title

### ISSUE THREAD

**Issue by ihtishamKhan** [thecyberworld/thecyberhub.org#195]
### Describe the bug

Upcoming events title should not be rendered when there is no upcoming events

I have done with the logic, I can create a pull request after the first one is approved I think. Pull Request: #194 
Please assign this issue to me as well

### To Reproduce

To reproduce this bug

1.  Remove data for upcoming events from ```components/Events/EventsData/EventsData.jsx``` if there is any
2. And go to ```/events```
3. You will see Upcoming Events title without data below that 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
I think that issue also got resoled, try now
