### ISSUE TITLE
[BUG] Footer is floating on zoom out, improve layout so footer will always be at bottom

### ISSUE THREAD

**Issue by nirajpdn** [thecyberworld/thecyberhub.org#199]
### Describe the bug

The layout will be better if the footer sticks always at the bottom even if there is no content in the page.

### To Reproduce

Website: https://www.thecyberhub.org/blogs
Local: http://localhost:3000/blogs

### Expected Behavior

Footer sticks at the bottom.

### Screenshot/ Video

<img width="917" alt="Screen Shot 2022-10-16 at 23 22 01" src="https://user-images.githubusercontent.com/59108522/196049898-4a1f3b8d-ea93-4b89-a2b6-6c2d4b9f48cf.png">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
hey @nirajpdn 
Thanks for submitting this issue

**Comment by kabir0x23** [comment]
If you are interested in this issue, let us know, will assign this issue to you.

**Comment by nirajpdn** [comment]
@kabir0x23 Sure. I will work on it after completing #185

**Comment by kabir0x23** [comment]
> @kabir0x23 Sure. I will work on it after completing #185

Okay nice

**Comment by jaswindersingh2601** [comment]
@kabir0x23 please assign this issue to me.

**Comment by jaswindersingh2601** [comment]
assign this issue to me, I am interested to work on this.

**Comment by kabir0x23** [comment]
> assign this issue to me, I am interested to work on this.

Awesome, I have assigned this issue to you

**Comment by nirajpdn** [comment]
Is this issue resolved ?

**Comment by kabir0x23** [comment]
> Is this issue resolved ?

Nope, this issue is still available.

**Comment by nirajpdn** [comment]
Assign it to me.

**Comment by kabir0x23** [comment]
Done
