### ISSUE TITLE
[BUG] non-responsive Job section

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#200]
### Describe the bug

Jobs page is non-responsive on wide screens 

![image](https://user-images.githubusercontent.com/44284877/196051209-22889be5-0705-40b8-aa33-a1f84f5893b4.png)

![image](https://user-images.githubusercontent.com/44284877/196051201-c8727747-2060-4bb1-8a20-f75edddad06c.png)

### To Reproduce

https://www.thecyberhub.org/prep/jobs

### Expected Behavior
Jobs card should look like these (cards in the center, with the same width )
![image](https://user-images.githubusercontent.com/44284877/196491161-358a209b-d559-45bc-afe3-61b47ed37397.png)

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/44284877/196051229-e9b1b04b-000f-4614-a15c-ce6585c70dab.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by javamultiplex** [comment]
Hi, I would like to work on this. Can you please assign to me?

**Comment by kabir0x23** [comment]
Awesome, I am assigning this issue to you.

**Comment by javamultiplex** [comment]
Thanks,  Can you please screen size for which this issue is coming?

**Comment by kabir0x23** [comment]
You can check it by zooming out on the screen.
and + we want to keep those jobs cards on center, when we do zooming out the screen, you can check out the blogs section as a preference.

**Comment by jaswindersingh2601** [comment]
I would like to work on this issue, could you assign this to me
