### ISSUE TITLE
[FEATURE] Add image behind the container

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#219]
### Detailed description

We have to add a image behind the container:

![image](https://user-images.githubusercontent.com/44284877/196449355-ae056506-fa15-4810-a4cd-ed8d0bbaa3a2.png)

### Context

You can see, above are four cards, you can usse
![image](https://user-images.githubusercontent.com/44284877/196456531-346ac13a-4842-401c-a00a-14f1be782734.png)

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Anuran12** [comment]
@kabir0x23  Hii I would like to work on this. Please assign this to me

**Comment by kabir0x23** [comment]
Awesome, I am assigning this issue to you.

**Comment by Anuran12** [comment]
@kabir0x23  Do I have to add that image for all project card or only one image behind project cards ?

**Comment by Anuran12** [comment]
@kabir0x23  ??

**Comment by kabir0x23** [comment]
> @kabir0x23 Do I have to add that image for all project card or only one image behind project cards ?

for now, you can add single image behinde all 4 cards

**Comment by kabir0x23** [comment]
Hey @Anuran12 ,
Are you working on this issue?

**Comment by Anuran12** [comment]
> > @kabir0x23 Do I have to add that image for all project card or only one image behind project cards ?
> 
> for now, you can add single image behinde all 4 cards

Okay..

**Comment by Anuran12** [comment]
> Hey @Anuran12 ,
> Are you working on this issue?

Yea

**Comment by Anuran12** [comment]
https://user-images.githubusercontent.com/104062485/197325148-06ad96aa-8378-48d9-88d6-056f8174ee4a.mp4

Is it okay ? @kabir0x23

**Comment by kabir0x23** [comment]
nope. you have to add that on the card as a background of the card, not in the container 

4 cards will have the same background, we will change the rest cards image

**Comment by Anuran12** [comment]
> nope. you have to add that on the card as a background of the card, not in the container 
> 
> 4 cards will have the same background, we will change the rest cards image

Ohh now i understand 🤦...

**Comment by Anuran12** [comment]
@kabir0x23  is it okay now ?

![image](https://user-images.githubusercontent.com/104062485/197328599-33342392-b9c8-4786-9562-872e3f7a3f4a.png)

**Comment by kabir0x23** [comment]
Awesome

You can use this overlay:
so background can be darker 
```js
export const Overlay = styled.div`
  width: 100%;
  height: 100%;
  position: absolute;
  background: #010606;
  opacity: 0.8;
`;
```

thank you

**Comment by Anuran12** [comment]
@kabir0x23 Sorry i am unable to use the overlay. I guess because i added the background image in css. see

![image](https://user-images.githubusercontent.com/104062485/197334027-725a0702-3e52-4926-b498-d89217bc52f7.png)

**Comment by kabir0x23** [comment]
Okay, 
You can raise the PR, we will mange that from our end

Thanks

**Comment by Anuran12** [comment]
@kabir0x23  Done
