### ISSUE TITLE
[Contact Section] Add a contact section in the navbar

### ISSUE THREAD

**Issue by hitaarthh** [thecyberworld/thecyberhub.org#220]
### Detailed description

This will contain the different social accounts,and the contact section in the navbar will redirect or scroll down to those container making it accessible for the user to view the organization in LinkedIn, Twitter, Gitlab, GitHub etc.

### Context

This feature will benefit the organization to grow more and redirect the user to the other social media platforms other than the organization website, to make it look more impactful.

### Possible implementation

This can be simply added by creating another section in the component section in the JS framework and hence implementing it in a very simple and unique way.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey @hitaarthh 

Do you mean, like this? 
![image](https://user-images.githubusercontent.com/44284877/196490735-cc8fad8b-7bb5-4ea6-8394-63885d111d9c.png)

**Comment by hitaarthh** [comment]
@kabir0x23 i meant a contact section in the navbar, which will redirect to the bottom of the page, where you can add a section, like "Get In touch" and there we can give links and section and a box where we can send a message and receive it using php.

**Comment by kabir0x23** [comment]
> @kabir0x23 i meant a contact section in the navbar, which will redirect to the bottom of the page, where you can add a section, like "Get In touch" and there we can give links and a section and a box where we can send a message and receive it using php.

Understood (and that section is having in the todo list but)
React with PHP?
how?
