### ISSUE TITLE
[FEATURE] Add routing to the course page and add a sidebox to navigate yo get particular courses.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#221]
### Detailed description

Add routing to the course page and add a sidebox to navigate to get particular courses.

### Context

add a sidebox that contains a heading and when the user clicks on the particular heading , should get a particular courses

Example: clicks on Linux: now they should only get these two courses: 
![image](https://user-images.githubusercontent.com/44284877/196598362-512c6aa0-243c-4f38-8f96-949561bd6a0b.png)

### Possible implementation

You can use routes for navigation.
Side box to display headings.
You have to play only a particular data.

All of the data is coming from coursename_data.jsx files

### Additional information

Awesome 😄

Thanks for contributing to this project.

If you want to contribute more then must check out other open-source projects and communities:
- [Thecyberworld](https://github.com/thecyberworld).
- [Cryptoverse Web3](https://github.com/CryptoverseWeb3)
- [kabir0x23](https://github.com/kabir0x23)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
> Hey @kabir0x23, I would like to work on this issue. However, I have some questions:
> 
>     * Can we please explain what do we mean by sidebox here? Will it something like this (screenshot below, rough idea)?
> 
> 
> <img alt="Screenshot 2022-10-19 at 1 47 56 PM" width="1105" src="https://user-images.githubusercontent.com/41188167/196644054-b7789bc4-8487-40a4-96a5-d8214752b7d8.png">
> 
>     * When a user clicks on a particular heading, it will be navigated to a different page, right? For example, when click on linux, the route will change to `resources/courses/linux` and will only show linux courses

Yes, exactly

**Comment by kabir0x23** [comment]
> Hey @kabir0x23, I would like to work on this issue. However, I have some questions:

Great, I am assigning this issue to you.

**Comment by Aksa12** [comment]
Hey @kabir0x23, quick questions:

- What should be title of the sidebar containing all the courses? Is `All Courses` fine? or should it be something else?
- In the mobile view, the sidebox should be at top, right? (attached video) pls let me know if it needs any changes.

 

https://user-images.githubusercontent.com/41188167/196739897-8f2ace7f-1598-4097-9ee1-8bda53fe6a2a.mov

**Comment by kabir0x23** [comment]
Awesome,

> What should be title of the sidebar containing all the courses? Is All Courses fine? or should it be something else?

Yes, All Courses is fine.

> In the mobile view, the sidebox should be at top, right? (attached video) pls let me know if it needs any changes.

Like something dropdown on small devies.

You also can create new issue on this dropdown and work on that one

**Comment by Aksa12** [comment]
@kabir0x23 cool. Can you pls share an example for the dropdown design? I was thinking something like this (video attached, will add animation later for smooth transition). Is it okay or I can change it accordingly if you can provide an example. Thanks.

https://user-images.githubusercontent.com/41188167/196795522-7a3e868e-aba8-4374-a1fa-241bb00c3655.mov

**Comment by kabir0x23** [comment]
> @kabir0x23 cool. Can you pls share an example for the dropdown design? I was thinking something like this (video attached, will add animation later for smooth transition). Is it okay or I can change it accordingly if you can provide an example. Thanks.

Looking good.

How about this design:
![image](https://user-images.githubusercontent.com/44284877/196798929-c5158e1a-16cb-4cab-84b9-78598b7b7b63.png)

**Comment by Aksa12** [comment]
Hey @kabir0x23, please have a look at it now. 

https://user-images.githubusercontent.com/41188167/196908837-82c428de-b894-4e45-9e19-1d325d312a37.mov

**Comment by kabir0x23** [comment]
Hey @Aksa12 ,

This is looking awesome.

**Comment by Aksa12** [comment]
@kabir0x23 done in the linked PR. Please review.

**Comment by kabir0x23** [comment]
> @kabir0x23 done in the linked PR. Please review.

Great, we will review your PR and merge very soon. until then/If you are looking to contribute more to the open source, then you can give a look at other open issues or can create issues.

Thank you 😄.
