### ISSUE TITLE
[BUG] Improper alignment of events.

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#222]
### Describe the bug

Improper alignment of events.

### To Reproduce

link: https://www.thecyberhub.org/events

### Expected Behavior

Alignment should be equal

- You can create a separate component for the heading (using styled-components only)
and give a fix margins

- and can set the margin-top upcomming and pastevents components 
- also make sure to correct ongoing events (will be there on particular dates) 
 

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/44284877/196598784-9f670370-947c-4f0d-9995-3518c48db396.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Aksa12** [comment]
Hey @kabir0x23, I would like to work on this issue

**Comment by kabir0x23** [comment]
Awesome, I am assigning this issue to you.

**Comment by kabir0x23** [comment]
> @kabir0x23 Fixed in the linked PR

Great, we will review your PR and merge very soon. until then/If you are looking to contribute more to the open-source, then you can give a look at other open issues or can create issues.

Thank you 😄.
