### ISSUE TITLE
[FEATURE] New navbar design, big navbar

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#223]
### Detailed description

We have to create a big navbar onhover

![image](https://user-images.githubusercontent.com/44284877/196605208-4f66e55a-d266-4c53-8dd1-02ab588c7848.png)

### Context

_no_response_

### Additional information

If you need any help or have any doubts or questions let us know.

Thank you 😄.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Bzsmrf** [comment]
Sir , can i have the opportunity to do this task

**Comment by kabir0x23** [comment]
Awesome
Sure, I am assigning this issue to you.

**Comment by Bzsmrf** [comment]
![requirement](https://user-images.githubusercontent.com/92678867/196618098-3cf5ad4d-9b5c-46af-9415-ef4e9cc8875b.jpeg)
Sir is this what u imagined ?
1)Do I need to implement it in all the elements in the navbar?
2) I know that this solution is not aesthetic to the eye i will fix that , do u want me to add some brief about each element when the navbar extends like in the example image

**Comment by kabir0x23** [comment]
yes this kind of looks
1. no we just need to add only on learn right now
2. yes you can write something.
3. and last thing. bg: dark, color: white

Thank you

**Comment by Bzsmrf** [comment]
![1](https://user-images.githubusercontent.com/92678867/196626529-7e3218f9-69be-4287-8571-c67f2257a2e3.jpeg)
![2](https://user-images.githubusercontent.com/92678867/196626551-0d9cb140-c7ed-433e-867d-54f176cbb88d.jpeg)

![3](https://user-images.githubusercontent.com/92678867/196626585-e8b71766-736f-4fb1-8860-e681a89c2fef.jpeg)

**Comment by kabir0x23** [comment]
Suggestions:
- You can comment on the prep nav-itme for now
- nice, you can add more spaces:
![image](https://user-images.githubusercontent.com/44284877/196627278-58894506-67e7-46e4-89b0-0bc056a8fcfd.png)

our end goal is to look like this.

Thank you.

**Comment by Bzsmrf** [comment]
![image](https://user-images.githubusercontent.com/92678867/196632970-f6e4fb06-22ae-467b-8eb6-7a24d155b352.png)
