### ISSUE TITLE
[OTHER] Remove Unused Dropdown button from the jobs event 

### ISSUE THREAD

**Issue by jaswindersingh2601** [thecyberworld/thecyberhub.org#246]
### What would you like to share?

I suggest that the dropdown button on the jobs page is unnecessary. it does not do any work. 

## Screenshot/video
![image](https://user-images.githubusercontent.com/101857182/197188197-65dcfc15-8093-4878-a5cf-cabfb01d7eab.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaswindersingh2601** [comment]
I can fix this and the PR is ready to assign this to me.

**Comment by kabir0x23** [comment]
> I can fix this and the PR is ready to assign this to me.

Great, I am assigning this issue to you.
