### ISSUE TITLE
[BUG] Navbar width overflowing 

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#247]
### Describe the bug
Navbar width overflowing 

![image](https://user-images.githubusercontent.com/44284877/197192574-8fb76ca9-33fc-4cd3-8123-2ce2cd874e5f.png)

### To Reproduce

1. visit: https://www.thecyberhub.org/
1. zoom the scene
2. hover on the learn

### Expected Behavior

This should not be overflowing

### Screenshot/ Video

![image](https://user-images.githubusercontent.com/44284877/197192343-d722774e-8a35-4613-a5b3-b30154091560.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by jaswindersingh2601** [comment]
Assign this issue to me i am interested to work on it .

**Comment by jaswindersingh2601** [comment]
Assign this issue to me I am interested to work on it .
