### ISSUE TITLE
[DOCS] <description> Adding more info in Readme

### ISSUE THREAD

**Issue by grow-xd** [thecyberworld/thecyberhub.org#261]
### Description

We can add more info the readme page as it does not show any general information about Thecyberhub and its use
I will also redesign the Readme and to make it more good looking by adding table of contents and using badges where required or making new sections like contact me.

### Additional information

I would like to work on this issue

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Sure, nice idea
and make sure to not make it too long

i am assigning this issue.

**Comment by grow-xd** [comment]
I am done with the changes please check https://github.com/grow-xd/thecyberhub.org if its looking good
I will send the pr

**Comment by kabir0x23** [comment]
nice, Send the pr i will send suggestions later on the PR

**Comment by grow-xd** [comment]
sent
