### ISSUE TITLE
[BUG] Sidebar Dropdown issue

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#290]
### Describe the bug

Sidebard Dropdown issue

### To Reproduce

when we click on the sidebar dropdown item, it does not close the whole sidebar

### Expected Behavior

When we click on the sidebar
- when we click on the natives of the dropdown, it should also display the close button or should be closed by clicking on the same navigate
- when we click on the sidebar dropdown, it should close the dropdown + sidebar too 

If you will have questions or doubts, you can ask them below.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by sanketshevare** [comment]
Hey @kabir0x23  you mean when we open nested list and close the outer list it should also close inner list, right?

**Comment by kabir0x23** [comment]
> Hey @kabir0x23 you mean when we open the nested list and close the outer list it should also close the inner list, right?

Hey @sanketshevare,

Yes, like that.

and some issues in the sidebar:
1. There should be a button to close this nested dropdown: 
![image](https://user-images.githubusercontent.com/44284877/205093172-567f085d-9ca4-4fbd-a8e7-10d6454838ab.png)

2. When we click on the cross button it should also go back to the prev state, for example, 
  - when we close the sidebar while in the nested dropdown and when we reopen the sidebar, again nestest sidebar is still there

3. When we click on the nested dropdown, it should also close the whole navbar.

**Comment by sanketshevare** [comment]
Yes got it 👍 will work on this.

**Comment by kabir0x23** [comment]
> Yes got it 👍 will work on this.

Awesome, I am assigning this issue to you.
If you will have any doubts you can ask below.

Thank You 😄.

**Comment by kabir0x23** [comment]
And make sure to pull the code once. thanks

**Comment by sanketshevare** [comment]
Done will all changes
