### ISSUE TITLE
[BUG] Updating Blog is not working (branch: dev)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#330]
### Describe the bug

Update Blog is not working (branch: dev)

frontend: [https://github.com/thecyberworld/thecyberhub.org](https://github.com/thecyberworld/thecyberhub.org)

backend: [https://github.com/thecyberworld/api.thecyberhub.org](https://github.com/thecyberworld/api.thecyberhub.org)

### To Reproduce

Update Blog is not working (branch: dev)
dashboard > blogs > + button you w ill get the form

error is comming in 
in blog slice:
under updateBlog
const state = thunkAPI.getState();
getstate is undefined

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ryan-byte** [comment]
I would like to work on this issue.
