### ISSUE TITLE
[BUG] Add Comments on blogs are not working (working with API, not with fronend) on (dev: branch)

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#334]
### Describe the bug

Add Comments on blogs are not working (working with API, not with frontend) on (dev: branch)

### To Reproduce

backend:
- [repo link](https://github.com/thecyberworld/api.thecyberhub.org) fork, clone run this 
- then add your creds in env file

Fronend:
 ---
- create blog 
- visit the blog on the /blogs
- then add comments 

### Expected Behavior

If you need any help or detail regaurding this, you can ask belowregarding

thank you.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ryan-byte** [comment]
I would like to work in this issue.
