### ISSUE TITLE
[FEATURE] Improve the Profile Layout and design on [branch: dev]

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#345]
### Detailed description

Improve the layout and design of the blogs page
local: http://localhost:3000/blogs

![image](https://user-images.githubusercontent.com/44284877/210176546-aa62b693-2b94-458e-8f82-70b72525facb.png)

### Context

Code is on dev branch
you have to setup the backend and frontend
add your MongoDB url into the env on backend

frontend: https://github.com/thecyberworld/thecyberhub.org

backend: https://github.com/thecyberworld/api.thecyberhub.org

### Additional information

If you need any help, let us know below

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MostlyGenius** [comment]
Can you assign this issue to me?

**Comment by kabir0x23** [comment]
Hello @MostlyGenius , thanks for your interest in helping out with this issue! I'm happy to assign it to you. Please let me know if you have any questions or need any additional information to get started. Thanks again for your contribution!

**Comment by MostlyGenius** [comment]
Hey,
Do you want dummy posts?  I only see 2 currently so not sure what you are looking to do.   Super ready to blow your mind with my amazing skills..  thanks

**Comment by kabir0x23** [comment]
hey @MostlyGenius 
Which issue you are looking at?

We have created some issues (creating more. today), you can give a look

1. We are focusing on the Blogs page first
2. So if 
1. We

**Comment by kabir0x23** [comment]
hey @MostlyGenius 

okay i got it
you have to check dev branch 
on main brnach that is dummy data 
on dev branch we are working

you can setup front-and-backend to work on those issues

Please let me know if you have any questions or need any additional information to get started.
