### ISSUE TITLE
[FEATURE] Improve or add new spinner/loader on loading components (not main website loader) on [branch: dev]

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#349]
### Detailed description

Examples:
- ![image](https://user-images.githubusercontent.com/44284877/210177083-a134172a-6b51-4b79-ba1a-1813b79f8b73.png)
- like above, where ever spinners are bieng used, create new or add new,
- do not change anything in that spinner.

### Context

.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by byte-king** [comment]
Hi @kabir0x23, I want to work on this issue.

**Comment by kabir0x23** [comment]
@byte-king 

this issue has been resolved, can you work on other issues?

**Comment by byte-king** [comment]
Sure.
