### ISSUE TITLE
<FEATURE>ADDING MEMBERS TAB BRANCH=dev

### ISSUE THREAD

**Issue by Ekankth** [thecyberworld/thecyberhub.org#363]
### Detailed description

Hi Team
Add a Members Tab Next to Sponsors Tab and add the members name with their roles and skills and their online availability time.

### Context

It will be helpful as The New visitors on website can get to know about the members and the help they want they will follow a particular time that will also help the admins and Developers and members to get sorted out of the problem fast

### Possible implementation

React Js

### Additional information

Thanks 

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey @Ekankth 
It's a good idea, but we don;t think so that we need to display members, we are a community of 200k, so mentioning some and some not, will be not a good idea,

Thanks for your time

**Comment by Ekankth** [comment]
> Hey @Ekankth It's a good idea, but we don;t think so that we need to display members, we are a community of 200k, so mentioning some and some not, will be not a good idea,
> 
> Thanks for your time

HI DEAR
WE DONT HAVE TO DISPLAY ALL MEMBERS WE JUST HAVE TO DISPLAY OUR OWNER AND ADMINS

**Comment by kabir0x23** [comment]
> > Hey @Ekankth It's a good idea, but we don;t think so that we need to display members, we are a community of 200k, so mentioning some and some not, will be not a good idea,
> > Thanks for your time
> 
> HI DEAR WE DONT HAVE TO DISPLAY ALL MEMBERS WE JUST HAVE TO DISPLAY OUR OWNER AND ADMINS

we have implementd contact form and included discord link.

if you have another ideam let us know
thank u
