### ISSUE TITLE
User Option dropdown doesn't close if click outside of it or scroll

### ISSUE THREAD

**Issue by s2sharpit** [thecyberworld/thecyberhub.org#384]
### Describe the bug

NOTE:  PROFILE DROPDOWN IS USED INSTEAD OF USER OPTION DROPDOWN AT SOME PLACES.

When the profile dropdown is open and clicks outside of it or scroll, it should close the profile dropdown.

### To Reproduce

Click on the Profile dropdown, in the top right corner to open it.
Click outside of it or try scrolling.
The Profile dropdown does not close on clicking outside or scrolling.

### Expected Behavior

The Profile dropdown should close if click outside of it or on scrolling.

### Screenshot/ Video

https://user-images.githubusercontent.com/104740281/225421168-5ea5aff8-6a66-4d40-bc4e-facac5152214.mp4

![image](https://user-images.githubusercontent.com/104740281/225421244-569a6372-b9e3-4e6b-aa79-a7bbe728517e.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by kabir0x23** [comment]
Hey @s2sharpit 
Thank you for creating an issue for this one

I am assigning this issue to u.

If u will have any questions or doubts, feel free to ask below
Thank u.

**Comment by s2sharpit** [comment]
I've made the necessary changes and have issued a PR, please check it out.
