### ISSUE TITLE
[FEATURE] Infinite scroll

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#98]
### Detailed description

- Add a limited number of news on the home page
- Set infinite scroll 
  - 5 news on the main screen, while scrolling load more news

### Context

- User will get more news
- no need for pagination if we use infinite scroll

### Possible implementation

![image](https://user-images.githubusercontent.com/44284877/192694709-29f2eba8-3a88-471e-800a-b6e35fe867db.png)

also, add a loading icon the end of the screen while fetching news.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Tusharjain123** [comment]
Hey Can I work on this issue?

**Comment by kabir0x23** [comment]
> Hey Can I work on this issue?

- Yes, you can
- We will assign this issue to you.

**Comment by kabir0x23** [comment]
> Hey Can I work on this issue?

Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

+ You will get more green squares.

**Comment by kabir0x23** [comment]
Hello @Tusharjain123 
any progress?

**Comment by Tusharjain123** [comment]
> Hello @Tusharjain123 any progress?

I am working on it

**Comment by kabir0x23** [comment]
> > Hello @Tusharjain123 any progress?
> 
> I am working on it

Awesome, I am assigning this issue to you.
If you will have any doubts and questions, let us know.

**Comment by Tusharjain123** [comment]
Where should I add the infinite scroll feature because in website there is no cybernews column?
![thecyberworld - Google Chrome 02-10-2022 07_28_47](https://user-images.githubusercontent.com/103761473/193443613-f9fb820d-9d26-4975-8bf1-bfed81f0d548.png)

**Comment by kabir0x23** [comment]
> Where should I add the infinite scroll feature because in website there is no cybernews column? ![thecyberworld - Google Chrome 02-10-2022 07_28_47](https://user-images.githubusercontent.com/103761473/193443613-f9fb820d-9d26-4975-8bf1-bfed81f0d548.png)

there is, under resoruces section 
https://www.thecyberhub.org/resources/cybernews

If you will have any doubts and questions, let us know.

**Comment by Tusharjain123** [comment]
> > Where should I add the infinite scroll feature because in website there is no cybernews column? ![thecyberworld - Google Chrome 02-10-2022 07_28_47](https://user-images.githubusercontent.com/103761473/193443613-f9fb820d-9d26-4975-8bf1-bfed81f0d548.png)
> 
> there is, under resoruces section https://www.thecyberhub.org/resources/cybernews
> 
> If you will have any doubts and questions, let us know.

ok thanks

**Comment by kabir0x23** [comment]
Hey, @andreaevolo Any progress?

If you need any help let me know...

**Comment by aishwarya-mali** [comment]
@kabir0x23 Can I work on this?

**Comment by kabir0x23** [comment]
> @kabir0x23 Can I work on this?

sure, i am assigning you this issue

**Comment by aishwarya-mali** [comment]
@kabir0x23 I can't see news section on Home page. Can you tell me how to find it?

**Comment by kabir0x23** [comment]
> @kabir0x23 I can't see the news section on the Home page. Can you tell me how to find it?

There is a routing issue in the News section since we changes the navbar design, and we didn't notice that till now.
Will you be able to fix that routing path?
let me know, otherwise will fix it my self.

Thanks

**Comment by aishwarya-mali** [comment]
> 

I'll see how it goes and let you know.

**Comment by kabir0x23** [comment]
> I'll see how it goes and let you know.

Awesome 👍

**Comment by aishwarya-mali** [comment]
@kabir0x23 I have fixed the routing issue for News which is under Learn Dropdown. Can you confirm where to implement infinite scroll as I can't see news on home page? or am I missing something.

**Comment by kabir0x23** [comment]
> @kabir0x23 I have fixed the routing issue for News which is under Learn Dropdown. Can you confirm where to implement infinite scroll as I can't see news on the home page? or am I missing something?

is NEWS visible under learn > news section?
after you open that NEWS section?

if not 
create an issue on fixing news routing and send the PR.

and then I can give a look at this issue.

**Comment by aishwarya-mali** [comment]
> is NEWS visible under learn > news section?
> after you open that NEWS section?

Yes it is visible then.
![image](https://user-images.githubusercontent.com/43086476/195979146-07eb741f-ba8e-4eb7-b16f-890c6efaac02.png)

**Comment by kabir0x23** [comment]
> > is NEWS visible under learn > news section?
> > after you open that NEWS section?
> 
> Yes it is visible then. ![image](https://user-images.githubusercontent.com/43086476/195979146-07eb741f-ba8e-4eb7-b16f-890c6efaac02.png)

yes, have to implement it here.

**Comment by aishwarya-mali** [comment]
@kabir0x23 Do I raise a PR for that fix or is it okay to do it with this issue?

**Comment by kabir0x23** [comment]
this same feature we  have impemented here before
https://github.com/CryptoverseWeb3/cryptoverseWeb3.com

if you got stuck anywhere, you can checkout this code.


Thank you.

**Comment by kabir0x23** [comment]
> @kabir0x23 Do I raise a PR for that fix or is it okay to do it with this issue?

Yes you can raise a one pr for both fixes
