### ISSUE TITLE
[FEATURE] Blogs page

### ISSUE THREAD

**Issue by kabir0x23** [thecyberworld/thecyberhub.org#99]
### Detailed description

Add a Blog section to the site
Can be made using React + styled-components.
- Add dummy data after completing this page, we will add backend later on.
### Context

Blogs plays important role in learning

### Possible implementation

Example: 👇
- You can make this type UI under the blog section.
- https://www.thecyberhub.org/resources/blogs

![image](https://user-images.githubusercontent.com/44284877/192741856-58072b73-e13f-4722-a032-fc172b5dd152.png)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by aritroCoder** [comment]
can you assign it to me? I know some react development

**Comment by kabir0x23** [comment]
> can you assign it to me? I know some react development

Yes sure 🧑‍💻

**Comment by aritroCoder** [comment]
![image](https://user-images.githubusercontent.com/92646038/192738624-d3901f61-05c7-4c7b-84d9-d587b2f27f68.png)

Is this design okay? You can suggest some more improvements

**Comment by kabir0x23** [comment]
> ![image](https://user-images.githubusercontent.com/92646038/192738624-d3901f61-05c7-4c7b-84d9-d587b2f27f68.png)
> 
> Is this design okay? You can suggest some more improvements

Yes, this looks good, 

suggestions:
make sure to check the reference: I have updated the example 
![image](https://user-images.githubusercontent.com/44284877/192741856-58072b73-e13f-4722-a032-fc172b5dd152.png)

**Comment by kabir0x23** [comment]
> can you assign it to me? I know some react development

Will you checkout this repository frist?
https://github.com/CryptoverseWeb3/git-github-practice

+ You will get more green squares

**Comment by kabir0x23** [comment]
> > > can you assign it to me? I know some react development
> > 
> > 
> > Will you checkout this repository frist? https://github.com/CryptoverseWeb3/git-github-practice
> > 
> > * You will get more green squares
> 
> Yeah I checked it, will it be counted for hacktoberfest or I can make the PR now only?

git-github-practice will not count as hacktober fest.
and yes you can make PR now.

**Comment by aritroCoder** [comment]
![image](https://user-images.githubusercontent.com/92646038/192849974-3c856b17-c130-4d52-92aa-ccbce3368662.png)

Here, I have updated the design

**Comment by kabir0x23** [comment]
> ![image](https://user-images.githubusercontent.com/92646038/192849974-3c856b17-c130-4d52-92aa-ccbce3368662.png)
> 
> Here, I have updated the design

Nice, this is looking good.
Some suggestions:
- reduce the text to 2-3 lines
- add an image above the heading.

**Comment by kabir0x23** [comment]
> ![image](https://user-images.githubusercontent.com/92646038/193101765-41863962-7973-417a-a6a5-e974bb70dce7.png)
> 
> @kabir0x23 Please confirm if this is all right

Awesome.
Can I know, which technologies are being used in making blog page by you?

**Comment by aritroCoder** [comment]
You can check the code, I have only use react and pure CSS

**Comment by kabir0x23** [comment]
> You can check the code, I have only used react and pure CSS

Nice work, good.
Have you worked with styled-components before?

**Comment by aritroCoder** [comment]
> You can check the code, I have only used react and pure CSS

Here is the code

**Comment by kabir0x23** [comment]
> > You can check the code, I have only used react and pure CSS
> 
> Above is the code

Yes, I have checked the code
Good work.

1st thing, never push the code on the main branch directly
- always create branches 
- example. you forked the repo(version: 10.0)
- now you directly push that code on your repo: (version increased: 13.0)
- now when you submit a PR, after merging(will become 14.)

just always create branches:
- fork the repo
- create new branches
- and then send those branches in PRs


With branches, all can work on different parts of code

Now there could be the chances of conflicts in the code.

**Comment by aritroCoder** [comment]
Thanks, I have created a new branch, will make the PR from there

**Comment by kabir0x23** [comment]
> Thanks, I have created a new branch, will make the PR from there

Good 👍
